### PR TITLE
Add Travis testing configuration

### PR DESCRIPTION
**Pull request by noloader**
This check-in adds Travis CI testing

If you have a Travis account tied to your GitHub account, then check-ins will trigger automatic builds and produce results like [Noloader | pveclib](https://travis-ci.org/github/noloader/pveclib/builds).

### CODE REVIEW

**Comment by noloader** [comment]
@munroesj52,

I'm wondering why this was not merged. Is there something wrong with this PR?

**Comment by munroesj52** [comment]
Still looking, and not sure all those changes are required.

**Comment by munroesj52** [comment]
Still don't still down know what travis is. I was very focused on other issues, 

For now I need to focus on completing the clang and IFUNC integration. Then I MUST focus on the document for "putting the library in PVECLIB. This includes dynamic IFUNC binding for platform specific codes. This is something I promised to the Fedora community. The clang adventure has been a bit of a distraction and blew my first solution (#pragma GCC target) out of the water.

**Comment by munroesj52** [comment]
So I am still not sure about this. I was planning to submit the version bump (1.0.4) to Fedora rawhide CI.

Not clear what the free vs priced versions of travis provide. Can't see what platforms are supported in the free version and "self hosted" version is $35/month. Does travic connect to GCC compile farm?

**Pull request closed without merging**
